
# COPCOIN PROJESI ANA BAGLANTI AYARLARI 

# -- 1 PostgreSQL Baglanti Bilgileri --

# Local'de docker-compose ile ayaga kaldirdigimiz PostgreSQL veritabanina baglaniyoruz.
spring.datasource.url=jdbc:postgresql://localhost:5432/cryptopal
# docker-compose.yml dosyasinda belirttigimiz root kullanici adi ve sifresiyle eşleşmesi önemli bu yüzden bunu da eklemeliyim:
spring.datasource.username=postgres
spring.datasource.password=secretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# -- 2 Hibernate / JPA Yapilandirmasi --
# veritabanımız PosstgreSQL olduğundan soorgularımızı PostgreSQL formatinda uetmemiz gerekiyor 
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Hatalari ve sorgulari terminalden kolayca takip edebilmek icin SQL loglarini acik biraktim 
spring.jpa.show-sql=true
# Tablolari schema.sql ile kendimiz kurdugumuz icin Hibernatein dokunmasini engelledik çünkü bu veri kaybına sebeb olabilir.  sadece kontrol etmesi yeterli (validate) 
spring.jpa.hibernate.ddl-auto=validate

# -- 3. Redis Baglantisi --
# Anlik fiyat ve token verilerini cache lemek icin local Redis portunu bagladik
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Swagger UI URL Ayarı
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
# Spring Boot'un PostgreSQL için data.sql dosyasını zorunlu çalıştırma ayarı
spring.sql.init.mode=always

# -- 4. Google Gemini AI Entegrasyon Ayarları --
# Yapay zeka sorguları için resmi Google Gemini API adresini ve çevre değişkeninden beslenen API anahtarını tanımladık.
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
gemini.api.key=${GEMINI_API_KEY:}